# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "BUH87VB3YK",
      issuer_id: "69a6de81-3e76-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_BUH87VB3YK.p8",
      duration: 1200, # optional (maximum 1200)
      # in_house: false # optional but may be required if using match/sigh
    )

    increment_build_number(xcodeproj: "./jesseapp.xcodeproj")

    build_app(
      workspace: "./jesseapp.xcworkspace",
      scheme: "jesseapp",
      configuration: "Release",
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      uses_non_exempt_encryption: false
    )
  end

end
